# BEGIN REMINDER API
server {
    listen 80;
    server_name reminder-api.wwmty.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
# END REMINDER API
