# 微信小程序配置示例
# 请根据实际情况修改配置值
wechat:
  miniprogram:
    # 小程序AppID（必填）
    appid: your_miniprogram_appid_here
    # 小程序AppSecret（必填）
    secret: your_miniprogram_secret_here
    # 微信API基础URL（一般不需要修改）
    api-base-url: https://api.weixin.qq.com
    # 获取session_key的URL路径（一般不需要修改）
    jscode2session-url: /sns/jscode2session
    # 连接超时时间（毫秒）
    connect-timeout: 5000
    # 读取超时时间（毫秒）
    read-timeout: 10000
  
  # 订阅消息配置
  notification:
    # 订阅消息模板ID（必填）
    template-id: your_template_id_here
    # 点击消息跳转的小程序页面路径（相对于小程序根目录）
    page: pages/index/index

# 日志配置
logging:
  level:
    com.core.reminder.service.WechatApiService: DEBUG
    com.core.reminder.service.WechatAuthService: DEBUG
    com.core.reminder.controller.WechatAuthController: DEBUG
    com.task.reminder.sender.WechatNotificationSender: DEBUG 