# 基本的 Spring Boot 配置
spring:
  application:
    name: reminder
  # PostgreSQL 数据库配置
  datasource:
    url: jdbc:postgresql://123.57.175.66:5432/remind # 指向你的 PostgreSQL 数据库
    driverClassName: org.postgresql.Driver # PostgreSQL 驱动
    username: your_username # 你的数据库用户名
    password: '123456' # 你的数据库密码
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL 方言
    # 禁用自动 DDL (因为我们使用 schema.sql), 推荐 validate 或 none
    hibernate:
      ddl-auto: validate # 或 none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # 显式指定命名策略
    # 关闭SQL语句显示
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  # Quartz 配置 (使用内存 JobStore, 应用重启任务会丢失, 生产环境建议使用 JDBC JobStore)
  quartz:
    job-store-type: memory
  # 邮件配置 (至少需要 host 才能触发 JavaMailSender 自动配置)
  mail:
    host: smtp.example.com # 提供一个占位符值
    # port: 587
    # username: your-email@example.com
    # password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 日志配置 - 设置Hibernate日志级别为ERROR以隐藏SQL语句
logging:
  level:
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR

# JWT Settings
# IMPORTANT: Replace with a strong, base64-encoded secret key for production! (at least 512 bits / 86 chars for HS512)
# Generate one using: `openssl rand -base64 64` or similar secure method.
app:
  jwtSecret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlLCBzdHJvbmcsIGFuZCBzZWNyZXQga2V5IHRoYXQgc2hvdWxkIGJlIG11Y2ggbG9uZ2VyIGFuZCBiZXR0ZXIgZm9yIHByb2R1Y3Rpb24hCg==
  # JWT expiration time in milliseconds (e.g., 1 hour = 3600000, 1 day = 86400000)
  jwtExpirationInMs: 86400000 